__author__ = 'hs0490'
class ReverseComplement:

    def findReverseComplement(dnastring):
        newstring = ''
        for char in dnastring:
            if char == 'A':
                 newchar = 'T'
            elif char == 'T':
                 newchar = 'A'
            elif char == 'C':
                newchar = 'G'
            elif char == 'G':
                newchar = 'C'

            newstring += newchar

        return newstring

    print ''.join(reversed(findReverseComplement('GCACAATCGGGGTGACCTGGCTAACCGAATAAGGGGGAGGTAATTTTGACACGCATGGAATCTTATCCGCGCTACGGTGTCAACCCCGATTTCTGTTCCACGATCAGTCTACTGTTCTTATGTGCAATTGTGTTCACTAATGAGCGGCCCCGGAGAAAGTTGCAAATTGGCGGAGAGCATACCTGTCCCCGGGCACTATCGTGCACCTCCGTGTCCAACTAACAACACGCCGAAATAGAGTCCTTCAAAATTATACTAAGAGTCGGTGCCGTTTCTTAGGAATCAGGAATACACACTGTGGCCCTTTTGACTTAGGCTGACAAGACAAGCTCCGTGACCGGGGTTGTAGTCCATTCTTGAAGAGCTCAAGGTTAAGAGTGGCAGGCAGGCGGTGGAGGAAACATGCCAGTATGGACGAAATATAGACGTTACGGTGAACCGCTAAATGGCGAAGTCCTAATGGTCCTATTTGTTGGCCATAAGGACCCACCCGTTCGTTTGTGATCAAGCCGCAATTATTGTACTTCGACTACAGCATTAGTAGGATTTGTGGAACCATGCTTATCATCCGTCCTTGATGCCCGGAAAGCGCCGAATTCTTTGTAGCCGCTACATCCGATGCATGAAAGTGTTATCTATTTGATCATGAACCCTCCAACTTAAGGTACCCGGTACCTAACACTGAATATCGTCCCAGTTCAGAGGGCACAAATAATGGTGGCGTGAGACAGTAATTGGACATCTAGTTGACGAACCTCCCACCGCGACACGGCGGCAAACTACCGTCCCCTAAGCGTGTCACTCCTCGAGTGAGATTTTCTTTTGCAATCATAACGGCTAGTGGTTCTACAATAGTGTAGCCGCAAAGTACTTATTTTGCGGCCGAACACCAAGG')))



